### ISSUE TITLE
Error with newest versions?

### ISSUE THREAD

**Issue by yelch** [CalderaWP/cf-translate#19]
Thanks a lot for your plugin! I just found it a few days ago and I'm am very happy with it.
I wanted to make use of the translations addon, but it seems not to work:

I’ve created a form. Then I enter ‘Translation’, select the form and click ‘Load Form’ under ‘Choose language’ the ‘Select language’ dropdown is empty…
If I select a language in ‘Enter New language’ and press ‘Add language’ it loads the empty page https://_mydomain_/wp-admin/admin.php?cftrans_nonce_lang=_myformtag_

I’ve tried again on another wp installation (also 4.7.2 with 1.4.8 of caldera froms and 1.07 of the translation plugin), but this site uses barely other plugins (though of a conflict with the polylang plugin)… It seems not to be a conflict with another plugin…

Am I doing something wrong or is there a bug ?

**Comment by Shelob9** [comment]
This should be fixed via #21
