### ISSUE TITLE
Permanent delete of trashed entries in the entry pages

### ISSUE THREAD

**Issue by mdorchain** [CalderaWP/cf-translate#35]
Hi,

When browsing entry admin pages, there's no option to delete permanently the trash or to restore the entries. The only bulk options available are "Export entries" and "Move to Trash".
Shouldn't be the "Move to Trash" option removed and, "Restore" and "Delete Permanently" added for trashed elements ?

This bulk options are already working perfectly when the entries are accessed from the form, but not from the entry pages.

Thanks

Michael

**Comment by Shelob9** [comment]
@mdorchain This is a Caldera Forms issue right? If so can you re-open it in https://github.com/calderawp/caldera-forms/issues please?
